INSERT_ONE_BY_BYTE = "insert_one"
INSERT_ONE_BY_PATH = "insert_one_by_path"
INSERT_MANY_BY_BYTE = "insert_many_by_byte"
INSERT_MANY_BY_DIR = "insert_many_by_dir"
INSERT_MANY_BY_PATHS = "insert_many_by_paths"

QUERY_NEAREST_BY_CONTENT = "query_nearest_by_content"
QUERY_NEAREST_BY_STYLE = "query_nearest_by_style"
QUERY_FARTHEST_BY_CONTENT = "query_farthest_by_content"
QUERY_FARTHEST_BY_STYLE = "query_farthest_by_style"
QUERY_BY_TAG_ALL = "query_by_tag_all"
QUERY_BY_TAG_PARTIAL = "query_by_tag_partial"
QUERY_RANGE_BY_CONTENT = "query_range_by_content"
QUERY_RANGE_BY_STYLE = "query_range_by_style"
